### ISSUE TITLE
Compilation error with example 1; fix is minor change to library

### ISSUE THREAD

**Issue by ajakef** [sparkfun/SparkFun_I2C_GPS_Arduino_Library#12]
Running example 1 with a Sparkfun Redboard Artemis, with Wire 2.0.0 and Sparkfun I2C GPS library v1.0.5, I get the following compilation error: 

> /home/jake/Arduino/libraries/SparkFun_I2C_GPS_Reading_and_Control/src/SparkFun_I2C_GPS_Arduino_Library.cpp: In member function 'boolean I2CGPS::begin(TwoWire&, uint32_t)':
> /home/jake/Arduino/libraries/SparkFun_I2C_GPS_Reading_and_Control/src/SparkFun_I2C_GPS_Arduino_Library.cpp:52:20: error: call of overloaded 'write(int)' is ambiguous
>    _i2cPort->write(0); //Write dummy value
>                     ^
> In file included from /home/jake/Arduino/libraries/SparkFun_I2C_GPS_Reading_and_Control/src/SparkFun_I2C_GPS_Arduino_Library.h:32,
>                  from /home/jake/Arduino/libraries/SparkFun_I2C_GPS_Reading_and_Control/src/SparkFun_I2C_GPS_Arduino_Library.cpp:28:
> /home/jake/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/libraries/Wire/src/Wire.h:42:20: note: candidate: 'virtual size_t arduino::MbedI2C::write(uint8_t)'
>      virtual size_t write(uint8_t data);
>                     ^~~~~
> In file included from /home/jake/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/core-api/api/ArduinoAPI.h:31,
>                  from /home/jake/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/Arduino.h:17,
>                  from /home/jake/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/sdk/ArduinoSDK.h:9,
>                  from <command-line>:
> /home/jake/.arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/core-api/api/Print.h:50:12: note: candidate: 'size_t arduino::Print::write(const char*)'
>      size_t write(const char *str) {
>             ^~~~~
> 
> exit status 1
> 
> Compilation error: exit status 1

It can be fixed by changing line 52 of SparkFun_I2C_GPS_Arduino_Library.cpp from
>  _i2cPort->write(0); //Write dummy value
to
>  _i2cPort->write((uint8_t)0); //Write dummy value

**Comment by nseidle** [comment]
Thanks for reporting. This is identical to issue #13. Should be fixed soon.
