### ISSUE TITLE
Error: call of overloaded 'write(int)' is ambiguous

### ISSUE THREAD

**Issue by gpabdo** [sparkfun/SparkFun_I2C_GPS_Arduino_Library#13]
I was receiving `Error: call of overloaded 'write(int)' is ambiguous` from `_i2cPort->write(0); //Write dummy value` not sure why it seems I am the only one to receive this message, but following the article here fixed it.

https://support.arduino.cc/hc/en-us/articles/360021722399-Error-call-of-overloaded-write-int-is-ambiguous

https://github.com/sparkfun/SparkFun_I2C_GPS_Arduino_Library/blob/master/src/SparkFun_I2C_GPS_Arduino_Library.cpp#L52

Will open a PR unless I am doing something wrong elsewhere.

**Comment by nseidle** [comment]
Very good. Different platforms have different levels of tolerance for ambiguity. This is a good fix. Thanks!
